allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

# pnpm 11+ workspace settings.
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - "@prisma/client"
  - prisma
  - "@prisma/engines"
  - esbuild

verifyDepsBeforeRun: false
